# -*- coding: utf-8 -*-
"""day1_numpy_pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUqbzZuk63cLaLa6nhLC0_FSaEccSOyM
"""

import numpy as np
#proyek numpy
arr2 = np.array([10, 20, 30, 40, 50]) #misal nilai gaji dalam juta , bos memerintahkan dan meminta:
                                        # menaikkan gaji sebesar 5 juta
                                        # melipatgandakan gaji
                                        # menghitung rata-ratanya
                                        # menentukan nilai tengahnya
                                        # meminta data gaji tertinngi, serta terendah)"""
for index, value in enumerate(arr2):
   print(f"ini adalah indeks ke{index + 1} dari array : ", (value)) # menyimpan data di komputer



print("gaji setelah di naikkan: ", arr2 + 5), #menambahkan 5 ke setiap data array
print('gaji setelah di lipatgandakan: ', arr2 * 2) #melipat gandakan nilai dari setiap array
print('rata-rata dari setiap gaji: ', np.mean(arr2)) #menghitung rata rata dari isi array
print('nilai tengah pada array gaji: ', np.median(arr2)) #menentukan nilai tengah dari isi array
print('gaji tertinngi: ', np.max(arr2)) #memfilter nilai tertinngi dari isi array
print('gaji terendah: ', np.min(arr2)) #memfilter nilai terrendah dari isi array
print('mengambil gaji pertama: ', arr2[0]) #indexing
print('menampilkan gaji 2-4: ', arr2[1:5] ) #slicing

#proyek pandas
import pandas as pd

#membuat Dataframe dari dictionary
data = {'Nama' : ['Dimas', 'Agus', 'Roihan'],
        'Usia': [19, 19, 20],
        'Gaji' : [500000000, 3000000, 2000000]
        } #dictionary
df = pd.DataFrame(data) #membuat dataframe dari dictionary
print("Dataframe dari dictionary:")
display(df) #menampilkan dataframe dengan format yang lebih rapi


df = pd.read_csv('data.csv', encoding='latin-1') #membaca file csv, menggunakan encoding 'latin-1'

print("\n5 data teratas dari data.csv:")
display(df.head()) #menampilkan 5 baris pertama dari dataframe dengan format yang lebih rapi


df_Quantity = df['Quantity'] #memfilter kolom Quantity
print("\n5 data teratas dari kolom Quantity:")
display(df_Quantity.head()) #menampilkan 5 data teratas dari kolom Quantity dengan format yang lebih rapi


print("\nRingkasan singkat data:")
display(df.describe()) #menampilkan deskripsi dari dataframe dengan format yang lebih rapi

print("\nInformasi data:")
df.info() #menampilkan informasi dari dataframe

print("\n5 data terakhir:")
display(df.tail()) #menampilkan 5 data terakhir dengan format yang lebih rapi