# -*- coding: utf-8 -*-
"""latihan day1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118Kq6Ky6VOpiWDh8Vxi_iWMtuyvYect0
"""

import pandas as pd
#mengakses data melalui url
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
print("\nRingkasan singkat data:")
display(df.describe()) #menampilkan deskripsi dari dataframe dengan format yang lebih rapi

print("\nInformasi data:")
df.info() #menampilkan informasi dari dataframe

print("\n5 data terakhir:")
display(df.tail()) #menampilkan 5 data terakhir dengan format yang lebih rapi



#melakukan pengecekan data dan pembersihan data
print(df.isnull().sum())  # Cek jumlah missing values
df = df.fillna({'Age': df['Age'].median(), 'Cabin': df['Cabin'].fillna('Unkown'), 'Embarked': df['Embarked'].mode()[0]})  # mengisi data kosong dengan median/Unknown
print('data yabg telah siap pakai; ')
display(df)

df.to_csv('titanic_clean.csv', index=False)
from google.colab import files

# Nama file CSV yang akan disimpan.
# index=False → Menghindari penyimpanan index Pandas di file CSV.

df_clean = pd.read_csv('titanic_clean.csv')
print(df_clean.head())
files.download('titanic_clean.csv')

import pandas as pd
import numpy as np

total_penumpang = df['PassengerId'].sum()
print(f'Total penumpang: {total_penumpang}')

# Hitung jumlah penumpang selamat & tidak selamat
survival_counts = df['Survived'].value_counts()

# Hitung persentase
percentage_survived = (survival_counts[1] / len(df)) * 100
percentage_not_survived = (survival_counts[0] / len(df)) * 100

print(f"Penumpang Selamat: {percentage_survived:.2f}%")
print(f"Penumpang Tidak Selamat: {percentage_not_survived:.2f}%")

rata_rata_umur = np.mean(df['Age'])
print(f'Rata-rata umur penumpang: {rata_rata_umur}')

# Hitung jumlah penumpang berdasarkan kelas tiket
pclass_counts = df['Pclass'].value_counts().sort_index()

print(pclass_counts)

survival_by_sex = df.groupby("Sex")["Survived"].value_counts(normalize=True) * 100
print(survival_by_sex)

#.groupby() untuk menghitung jumlah penumpang yang selamat & tidak selamat berdasarkan jenis kelamin.
#Gunakan .value_counts() atau crosstab() sebagai alternatif untuk membandingkan data.

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x="Sex", hue="Survived", data=df)
plt.title("Hubungan Jenis Kelamin dan Keselamatan")
plt.show()

sns.barplot(x="Pclass", y="Pclass", data=df, estimator=len)
plt.title("Bar Chart Jumlah Penumpang Menurut Kelasnya")
plt.ylabel("Jumlah") # Beri label sumbu y sebagai jumlah
plt.show()

import matplotlib.pyplot as plt

survived_counts = df["Survived"].value_counts()
labels = ["Tidak Selamat", "Selamat"]
colors = ["red", "green"]

plt.pie(survived_counts, labels=labels, autopct="%1.1f%%", colors=colors, startangle=90)
plt.title("Persentase Penumpang yang Selamat vs. Tidak Selamat")
plt.show()

import seaborn as sns

plt.figure(figsize=(8, 5))
sns.histplot(df["Age"].dropna(), bins=30, kde=True, color="blue")
plt.title("Distribusi Umur Penumpang Titanic")
plt.xlabel("Umur")
plt.ylabel("Jumlah Penumpang")
plt.show()

plt.figure(figsize=(8, 5))
sns.boxplot(x="Pclass", y="Age", data=df, palette="coolwarm")
plt.title("Distribusi Umur Berdasarkan Kelas Tiket")
plt.xlabel("Kelas Tiket")
plt.ylabel("Umur")
plt.show()